### ISSUE TITLE
Syntax error on model definition file example

### ISSUE THREAD

**Issue by BrcRs** [BrcRs/table-arrangement#6]
`Traceback (most recent call last):
  File ".\interpreter.py", line 150, in <module>
    main()
  File ".\interpreter.py", line 148, in main
    problem = load_problem(sys.argv[1])
  File ".\interpreter.py", line 61, in load_problem
    raise SyntaxError("Lonely blank on line " + str(nline))
SyntaxError: Lonely blank on line 1`

**Comment by BrcRs** [comment]
I'll need to replace \t with four blanks
